/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.endicott.mocean.medievalmarket;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mocea
 */
public class Marketplace extends javax.swing.JFrame {
    ArrayList<GameItem> playerInv;
    ArrayList<GameItem> merchInv;
    int playerGold;
    private DefaultListModel<String> playerdlm;
    private DefaultListModel<String> merchdlm;
    private int selectionPlayer;
    private int selectionMerch;
    /**
     * Creates new form Marketplace
     */
    public Marketplace() {
        //Creating the DLM's
        playerdlm = new DefaultListModel();
        merchdlm = new DefaultListModel();
       //Creating the array lists
        playerInv=new ArrayList();
        merchInv= new ArrayList();
        
        //creating the default items
        GameItem sword = new GameItem("Iron Broadsword",100,0," A Brutal weapon, Good for the ol' Slice and Dice.");
        GameItem exsword = new GameItem("ENCHANTED Iron Longsword", 250,0," With ancient Runic text along the blade, it can easily be able to take out a dragon");
        GameItem food = new GameItem("Apple",25,5, "From the local orchard. the merchant gets them in every day, right before sunrise");
        GameItem badfood= new GameItem("Rotten Tomato",5,-10, "The Merchant sells these moldy tomatos for the next time that stupid guy in town gets in trouble, or if you hate someone a lot");
        GameItem chararmor = new GameItem("Leather Armor", 90, 0,"This is armor that your mother bought you for your first adventure");
        GameItem charsword = new GameItem("Shortsword",80,0,"This sword has been passed down through the generations.");
        
        //adding the items to the list. 
        playerInv.add(chararmor);
        playerInv.add(charsword);
        merchInv.add(sword);
        merchInv.add(exsword);
        merchInv.add(food);
        merchInv.add(badfood);
        initComponents();
        
        // MO: Some hints:
        // making buttons disabled by default since nothing is selected
        // in either list yet.
        
        btnSell.setEnabled(false);
        btnBuy.setEnabled(false);
        btnVendorInfo.setEnabled(false);
        btnPlayerInfo.setEnabled(false);
        playerGold=300;
        jtfPlayersGold.setText(Integer.toString(playerGold));
     
          
        playerdlm.addElement(chararmor.getShort());
        playerdlm.addElement(charsword.getShort());
        
        merchdlm.addElement(sword.getShort());
        merchdlm.addElement(exsword.getShort());
        merchdlm.addElement(food.getShort());
        merchdlm.addElement(badfood.getShort());
        
        //TODO: show the amount of gold the player has in jtfPlayersGold
        // and lots more.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstPlayerItems = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstMerchItems = new javax.swing.JList<>();
        jtfPlayersGold = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        btnVendorInfo = new javax.swing.JButton();
        btnPlayerInfo = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Merchant Window");

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Player's Inventory"));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 239));

        jlstPlayerItems.setModel(playerdlm);
        jlstPlayerItems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlstPlayerItemsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlstPlayerItems);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seller's Inventory"));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 239));

        jlstMerchItems.setModel(merchdlm);
        jlstMerchItems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlstMerchItemsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jlstMerchItems);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jtfPlayersGold.setEditable(false);
        jtfPlayersGold.setText("300");
        jtfPlayersGold.setToolTipText("");

        jLabel1.setText("player's gold:");

        btnBuy.setText("Buy selected");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        btnVendorInfo.setText("Info");
        btnVendorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendorInfoActionPerformed(evt);
            }
        });

        btnPlayerInfo.setText("Info");
        btnPlayerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerInfoActionPerformed(evt);
            }
        });

        btnSell.setText("Sell Selected");
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnPlayerInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSell)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVendorInfo)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtfPlayersGold)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuy)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuy)
                    .addComponent(btnVendorInfo)
                    .addComponent(btnPlayerInfo)
                    .addComponent(btnSell))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPlayersGold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        
        if(merchInv.get(selectionMerch).getPrice()>playerGold){
            JOptionPane.showMessageDialog(null, "The player has insufficient funds to make this purchase");
        }
        else{
            playerGold= playerGold- merchInv.get(selectionMerch).getPrice();
            jtfPlayersGold.setText(Integer.toString(playerGold));
            playerInv.add(merchInv.get(selectionMerch));
            playerdlm.addElement(merchInv.get(selectionMerch).getShort());
            merchInv.remove(merchInv.get(selectionMerch));
            merchdlm.removeElementAt(selectionMerch);
            if(merchInv.isEmpty()){
                btnVendorInfo.setEnabled(false);
            }
              btnBuy.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnPlayerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerInfoActionPerformed
        // if the info button under the player inventory is clicked
        JOptionPane.showMessageDialog(null, playerInv.get(selectionPlayer).getDescript());
    }//GEN-LAST:event_btnPlayerInfoActionPerformed

    private void jlstPlayerItemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlstPlayerItemsValueChanged
        // this changes so that when a new item is clicked that it gives us the number throught selection
       if(evt.getValueIsAdjusting()){
           selectionPlayer=evt.getLastIndex();
           btnPlayerInfo.setEnabled(true);
           btnSell.setEnabled(true);
       }
    }//GEN-LAST:event_jlstPlayerItemsValueChanged

    private void jlstMerchItemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlstMerchItemsValueChanged
        // TODO add your handling code here:
        if(evt.getValueIsAdjusting()){
            selectionMerch= evt.getLastIndex();
            btnVendorInfo.setEnabled(true);
            btnBuy.setEnabled(true);
        }
    }//GEN-LAST:event_jlstMerchItemsValueChanged

    private void btnVendorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendorInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, merchInv.get(selectionMerch).getDescript());
    }//GEN-LAST:event_btnVendorInfoActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        playerGold= playerGold+ playerInv.get(selectionPlayer).getPrice();
        jtfPlayersGold.setText(Integer.toString(playerGold));
        merchInv.add(playerInv.get(selectionPlayer));
        merchdlm.addElement(playerInv.get(selectionPlayer).getShort());
        playerInv.remove(playerInv.get(selectionPlayer));
        playerdlm.removeElementAt(selectionPlayer);
        btnSell.setEnabled(false);
       
    }//GEN-LAST:event_btnSellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marketplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marketplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marketplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marketplace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marketplace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnPlayerInfo;
    private javax.swing.JButton btnSell;
    private javax.swing.JButton btnVendorInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> jlstMerchItems;
    private javax.swing.JList<String> jlstPlayerItems;
    private javax.swing.JTextField jtfPlayersGold;
    // End of variables declaration//GEN-END:variables
}
